### ISSUE TITLE
Práctica 4_Diseño BD Relacional

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/diseno-de-bases-de-datos-relacional-trabajo-is#2]
[Práctica 4_Diseño BD Relacional.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-bases-de-datos-relacional-trabajo-is/files/6333841/Practica.4_Diseno.BD.Relacional.pdf)

**Comment by Jaimer117** [comment]
20%cumple con lo de la rúbrica

**Comment by josealfredo79** [comment]
Favor de checar la lista de pedido...o el detalle de pedido en la bases de datos.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
